apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stoat-data-pvc
  namespace: stoat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
